// Generated by CoffeeScript 1.10.0
(function() {
  var $, child_process, run_du, run_ffprobe, run_ls, scroll_terminal;

  $ = require('jquery');

  child_process = require('child_process');

  run_ls = function() {
    var ls;
    ls = child_process.spawn('ls', ['-lah']);
    ls.stdout.on('data', function(data) {
      var ls_out;
      console.log("stdout: " + data);
      console.log(data.toString());
      ls_out = data.toString().replace(/(?:\r\n|\r|\n)/g, '<br />');
      $('#container').append(ls_out);
      return scroll_terminal();
    });
    ls.stderr.on('data', function(data) {
      return console.log("stderr: " + data);
    });
    return ls.on('close', function(code) {
      return console.log("child process exited with code " + code);
    });
  };

  run_ffprobe = function() {
    var ffprobe;
    ffprobe = child_process.spawn('ffprobe', ['-print_format', 'json', '/home/jason/code/canfee/canfee-out.mp4']);
    ffprobe.stderr.on('data', function(data) {
      var ffprobe_out;
      console.log("stderr: " + data);
      ffprobe_out = data.toString().replace(/(?:\r\n|\r|\n)/g, '<br>').replace('  ', '&nbsp;&nbsp;').replace("\t", '&nbsp;&nbsp;');
      $('#container').append(ffprobe_out);
      return scroll_terminal();
    });
    return ffprobe.on('close', function(code) {
      return console.log("child process exited with code " + code);
    });
  };

  run_du = function() {
    var du;
    du = child_process.spawn('du', ['-h', '.']);
    du.stdout.on('data', function(data) {
      var du_out;
      du_out = data.toString().replace(/(?:\r\n|\r|\n)/g, '<br>');
      console.log('du data');
      $('#container').append(du_out);
      return scroll_terminal();
    });
    return du.on('close', function() {
      return console.log('closed');
    });
  };

  scroll_terminal = function() {
    var myDiv;
    $('#container').append("<br><br>");
    myDiv = $("#container");
    return myDiv.animate({
      scrollTop: myDiv.prop("scrollHeight") - myDiv.height()
    }, 100);
  };

  $(document).ready(function() {
    $('#ls').on('click', run_ls);
    $(document).ready(function() {
      return $('#ffprobe').on('click', run_ffprobe);
    });
    return $(document).ready(function() {
      return $('#du').on('click', run_du);
    });
  });

}).call(this);
