// Generated by CoffeeScript 1.10.0
(function() {
  var $, async, electron, handle_files, hbs_render, modal, open_files_added_modal, prettysize, sharp;

  $ = require('jquery');

  hbs_render = require(__dirname + "/../javascripts/hbs_render");

  sharp = require('sharp');

  async = require('async');

  modal = null;

  prettysize = require('prettysize');

  electron = require('electron');

  handle_files = function(files) {
    var image_number, index;
    image_number = $('.image_number').html();
    index = image_number !== '' ? parseInt(image_number) : 0;
    return async.each(files, function(file, async_callback) {
      console.log(file);
      return sharp(file.path).limitInputPixels(2147483647).resize(null, 100).toFormat('png').toBuffer().then(function(output) {
        var image, line;
        image = output.toString('base64');
        line = hbs_render('file_row', {
          path: file.path,
          image: image,
          filesize: prettysize(file.size)
        });
        $('#container').prepend(line);
        index++;
        $('.image_number').html(index);
        $('#commands').show();
        return async_callback();
      });
    }, function() {
      modal.close();
      return new Notification(index + " image(s) added and ready to be processed!");
    });
  };

  open_files_added_modal = function(number) {
    $("#files-added-modal-number").html(number);
    modal = new Foundation.Reveal($('#files-added-modal'));
    return modal.open();
  };

  $(document).ready(function() {
    $(document).on('dragover,drop', function(e) {
      e.preventDefault();
      return false;
    });
    $('#dropzone').on('drop', function(e) {
      var files;
      e.preventDefault();
      console.log('dropped');
      files = e.originalEvent.dataTransfer.files;
      open_files_added_modal(files.length);
      handle_files(files);
      return $('#dropzone').removeClass('dragover');
    });
    $('#dropzone').on('dragover', function(e) {
      e.preventDefault();
      return false;
    });
    $('#dropzone').on('dragenter', function(e) {
      e.preventDefault();
      return $('#dropzone').addClass('dragover');
    });
    $('#dropzone').on('dragleave,dragend', function() {
      return false;
    });
    $('#file-select-trigger').on('click', function(e) {
      var input;
      e.preventDefault();
      input = $('#file-select-input');
      return input.click();
    });
    $('#file-select-input').on('change', function(e) {
      var files, input;
      input = $('#file-select-input');
      files = input[0].files;
      open_files_added_modal(files.length);
      return handle_files(files);
    });
    return $('#restart').on('click', function(e) {
      electron.remote.getCurrentWindow().reload();
      return e.preventDefault();
    });
  });

}).call(this);
