// Generated by CoffeeScript 1.10.0
(function() {
  var fs, handlebars;

  handlebars = require('handlebars');

  fs = require('fs');

  module.exports = function(template, variables) {
    var source, template_file;
    template_file = fs.readFileSync(__dirname + ("/../../app/views/templates/" + template + ".hbs"));
    source = template_file.toString();
    template = handlebars.compile(source);
    return template(variables);
  };

}).call(this);
