// Generated by CoffeeScript 1.10.0
(function() {
  var IIIFInfo, child_process, parsexml, util;

  parsexml = require('xml2js').parseString;

  child_process = require('child_process');

  util = require('util');

  IIIFInfo = (function() {
    function IIIFInfo(image_path) {
      this.image_path = image_path;
    }

    IIIFInfo.prototype.kdu_info = function() {
      var info, kdu_info_cmd, kdu_info_result;
      kdu_info_cmd = "kdu_jp2info -siz -boxes 1 -com -i " + this.image_path;
      info = null;
      kdu_info_result = child_process.execSync(kdu_info_cmd);
      parsexml(kdu_info_result, function(err, result) {
        return info = result;
      });
      return info;
    };

    IIIFInfo.prototype.info = function() {
      var codestream, info, jpc, kinfo;
      info = this.info_start();
      kinfo = this.kdu_info();
      jpc = kinfo.JP2_family_file.jp2c[0];
      codestream = jpc.codestream[0];
      info['height'] = parseInt(codestream.height[0]);
      info['width'] = parseInt(codestream.width[0]);
      return info;
    };

    IIIFInfo.prototype.info_start = function() {
      return {
        '@context': "http://iiif.io/api/image/2/context.json",
        'protocol': "http://iiif.io/api/image",
        '@id': "http://localhost:3000/" + (encodeURIComponent(this.image_path)),
        'profile': [
          "http://iiif.io/api/image/2/level2.json", {
            'qualities': ['default']
          }
        ]
      };
    };

    return IIIFInfo;

  })();

  module.exports = IIIFInfo;

}).call(this);
