// Generated by CoffeeScript 1.10.0
(function() {
  var $, check_install, check_interval, ipc_renderer, shell, which;

  $ = require('jquery');

  shell = require('electron').shell;

  ipc_renderer = require('electron').ipcRenderer;

  which = require('which');

  check_interval = void 0;

  check_install = function() {
    return which('kdu_compress', function(err, path) {
      if (path != null) {
        $('#kdu_compress-polling').hide();
        $('#retry-launch-section').show();
        return clearInterval(check_interval);
      }
    });
  };

  $(document).ready(function() {
    $('#open-install').on('click', function() {
      shell.openExternal('http://kakadusoftware.com/downloads/');
      $('#kdu_compress-polling').show();
      return check_interval = setInterval(function() {
        return check_install();
      }, 1000);
    });
    return $('#retry-launch').on('click', function() {
      return ipc_renderer.send('retry-launch');
    });
  });

}).call(this);
