// Generated by CoffeeScript 1.10.0
(function() {
  var $, check_install_kdu, check_install_opj, check_interval, ipc_renderer, shell, which;

  $ = require('jquery');

  shell = require('electron').shell;

  ipc_renderer = require('electron').ipcRenderer;

  which = require('which');

  check_interval = void 0;

  check_install_kdu = function() {
    return which('kdu_compresss', function(err, path) {
      if (path != null) {
        $('#kdu_compress-polling').hide();
        $('#retry-launch-section').show();
        $('#kdu_installed-launch').show();
        return clearInterval(check_interval);
      }
    });
  };

  check_install_opj = function() {
    return which('opj_compress', function(err, path) {
      if (path != null) {
        $('#opj_compress-polling').hide();
        $('#retry-launch-section').show();
        $('#opj_installed-launch').show();
        return clearInterval(check_interval);
      }
    });
  };

  $(document).ready(function() {
    $('#open-install-kdu').on('click', function() {
      shell.openExternal('http://kakadusoftware.com/downloads/');
      $('#kdu_compress-polling').show();
      return check_interval = setInterval(function() {
        return check_install_kdu();
      }, 1000);
    });
    $('#open-install-opj').on('click', function() {
      shell.openExternal('https://github.com/uclouvain/openjpeg');
      $('#opj_compress-polling').show();
      return check_interval = setInterval(function() {
        return check_install_opj();
      }, 1000);
    });
    return $('#retry-launch').on('click', function() {
      return ipc_renderer.send('retry-launch');
    });
  });

}).call(this);
