// Generated by CoffeeScript 1.10.0
(function() {
  var $, url;

  $ = require('jquery');

  url = require('url');

  $(document).ready(function() {
    var image_id, location, osd_config, viewer;
    location = url.parse(window.location.href, true);
    image_id = location.query.id;
    console.log(image_id);
    osd_config = {
      id: 'openseadragon',
      prefixUrl: '../../node_modules/openseadragon/build/openseadragon/images/',
      preserveViewport: true,
      visibilityRatio: 1,
      minZoomLevel: 1,
      defaultZoomLevel: 1,
      sequenceMode: true,
      tiles: [
        {
          scaleFactors: [1, 2, 4, 8, 16, 32],
          width: 1024
        }
      ],
      tileSources: []
    };
    osd_config['tileSources'].push("http://localhost:3000/" + (encodeURIComponent(image_id)) + "/info.json");
    console.log(osd_config);
    return viewer = OpenSeadragon(osd_config);
  });

}).call(this);
