// Generated by CoffeeScript 1.10.0
(function() {
  var $, electron, insert_output_dir, ipc_renderer, settings;

  $ = require('jquery');

  electron = require('electron');

  settings = electron.remote.getCurrentWindow().settings;

  ipc_renderer = require('electron').ipcRenderer;

  insert_output_dir = function() {
    return $('#output_dir').html(settings.get('output_dir'));
  };

  $(document).ready(function() {
    insert_output_dir();
    $('#change-output-directory').on('click', function() {
      return $('#file-select-input').click();
    });
    return $('#file-select-input').on('change', function(e) {
      var files, path;
      files = $('#file-select-input')[0].files;
      path = files[0].path;
      settings.set('output_dir', path);
      insert_output_dir();
      return ipc_renderer.send('open-mainwindow-if-not');
    });
  });

}).call(this);
