// Generated by CoffeeScript 1.10.0
(function() {
  var $, check_jp2_binary, current_window, electron, insert_output_dir, ipc_renderer, settings;

  $ = require('jquery');

  electron = require('electron');

  current_window = electron.remote.getCurrentWindow();

  settings = current_window.settings;

  ipc_renderer = require('electron').ipcRenderer;

  insert_output_dir = function() {
    return $('#output_dir').html(settings.get('output_dir'));
  };

  check_jp2_binary = function() {
    return $("#" + (settings.get('jp2_binary'))).prop('checked', true);
  };

  $(document).ready(function() {
    insert_output_dir();
    check_jp2_binary();
    $('#change-output-directory').on('click', function() {
      return $('#file-select-input').click();
    });
    $('#file-select-input').on('change', function(e) {
      var files, path;
      files = $('#file-select-input')[0].files;
      path = files[0].path;
      settings.set('output_dir', path);
      insert_output_dir();
      return ipc_renderer.send('open-mainwindow-if-not');
    });
    $('#jp2_binary').on('change', function(e) {
      return settings.set('jp2_binary', e.target.id);
    });
    return $('#close_window').on('click', function() {
      return current_window.close();
    });
  });

}).call(this);
